Check the implementation of various models

# Data

In [4]:
import altair as alt
import numpy as np
import polars as pl
import torch

from ts_uncertainty.plotting import plot_synthetic_sample
from ts_uncertainty.synthetic import SyntheticGenerator, SyntheticSample

alt.renderers.enable("jupyter", offline=True)
device = "cuda" if torch.cuda.is_available() else "cpu"

In [5]:
context_length = 48
horizon_length = 12

sin_gen = SyntheticGenerator(
    context_length=context_length,
    horizon=horizon_length,
    seasonal=True,
    periods=(24,),             # period of the sine
    n_periods=1,
    n_harmonics=1,             # 1 harmonic = pure sine, no extra shape
    level_range=(0.0, 0.0),    # centered at 0
    slope_range=(0.0, 0.0),    # no trend
    amplitude_range=(1.0, 1.0),
    noise=False,
    spikes=False,
    shift=False,
)
s = sin_gen.sample()
plot_synthetic_sample(s, title="Sin Sample")

# Timing Benchmark

In [ ]:
import torch.utils.benchmark as benchmark

def bench(model, x, train: bool, sub_label: str):
    model.train(train)
    if train:
        stmt = "model(x).sum().backward()"           # forward + backward
    else:
        stmt = "with torch.no_grad(): model(x)"      # forward only
    timer = benchmark.Timer(
        stmt=stmt,
        globals={"model": model, "x": x, "torch": torch},
        label="Transformer_Model",
        sub_label=sub_label,
        description="train" if train else "inference",
    )
    return timer.blocked_autorange(min_run_time=2.0)   # repeats until 2 s of measurements

# Model Implementation

## LSTM

In [14]:
from ts_uncertainty.models.lstm import LSTM_Model

In [ ]:
# model input and output shapes
x = torch.tensor(s.context).reshape(1, -1, 1).to(device)  # (B, T, V)
y = torch.tensor(s.target).reshape(1, -1, 1).to(device)  # (B, T, V)
x.shape, y.shape

In [19]:
lstm_cfg = {
    "input_size": 1,
    "target_size": 1,
    "horizon_length": horizon_length,
    "hidden_size": 32,
}
ref_model = LSTM_Model(
    **lstm_cfg,
    use_torch=True,
    init_constant=True,
).to(device)
my_model = LSTM_Model(
    **lstm_cfg,
    use_torch=False,
    init_constant=True,
).to(device)

out_ref = ref_model(x)
out_my = my_model(x)

print("Weights and biases are equal between the two models:")
print(torch.allclose(ref_model.lstm.weight_ih_l0, my_model.lstm.weight_ih))
print(torch.allclose(ref_model.lstm.weight_hh_l0, my_model.lstm.weight_hh))
print(torch.allclose(ref_model.lstm.bias_ih_l0, my_model.lstm.bias_ih))
print(torch.allclose(ref_model.lstm.bias_hh_l0, my_model.lstm.bias_hh))
print("Output of the two models are equal:")
print(torch.allclose(out_ref, out_my))

Weights and biases are equal between the two models:
True
True
True
True
Output of the two models are equal:
False

In [ ]:
results = []
for name, model in [("torch", ref_model), ("mine", my_model)]:
    for train in [False, True]:
        results.append(bench(model, x, train, f"{name:5s}"))
benchmark.Compare(results).print()

[-------- Transformer_Model --------]
             |  inference  |   train
1 threads: --------------------------
      torch  |     256.0   |   1132.1
      mine   |   16588.6   |  42192.5

Times are in microseconds (us).

## Transformer

In [16]:
from ts_uncertainty.models.transformer import Transformer_Model

In [ ]:
# model input and output shapes
x = torch.tensor(s.context).reshape(1, -1, 1).to(device)  # (B, T, V)
y = torch.tensor(s.target).reshape(1, -1, 1).to(device)  # (B, T, V)
x.shape, y.shape

In [21]:
transformer_cfg = {
    "input_size": 1,
    "target_size": 1,
    "horizon_length": 12,
    "d_model": 32,
    "nhead": 4,
    "num_encoder_layers": 2,
    "num_decoder_layers": 2,
    "dim_feedforward": 64,
    "dropout": 0.0,
}

ref_model = Transformer_Model(
    **transformer_cfg,
    use_torch=True,
    init_constant=True,
).to(device)
my_model = Transformer_Model(
    **transformer_cfg,
    use_torch=False,
    init_constant=True,
).to(device)

out_torch = ref_model(x)
out_mine = my_model(x)

print(out_torch.shape) 
print(
    f"match: {torch.allclose(out_torch, out_mine, atol=1e-5)}",
    f"max diff: {(out_torch - out_mine).abs().max():.2e}",
)

torch.Size([1, 12, 1])
match: True max diff: 0.00e+00

In [22]:
results = []
for name, model in [("torch", ref_model), ("mine", my_model)]:
    for train in [False, True]:
        results.append(bench(model, x, train, f"{name:5s}"))
benchmark.Compare(results).print()

[------- Transformer_Model -------]
             |  inference  |  train
1 threads: ------------------------
      torch  |     2.9     |   10.4
      mine   |     4.6     |   13.6

Times are in milliseconds (ms).

## Chronos-2

In [74]:
from ts_uncertainty.models.chronos2.scaling import compute_scale_stats, apply_scaling, invert_scaling
from ts_uncertainty.models.chronos2.patching import build_context_patches, build_future_patches
from ts_uncertainty.models.chronos2.embedding import ResidualBlock

In [76]:
# model input and output shapes
x = torch.tensor(s.context).reshape(1, 1, -1).to(device)  # (B, V, T)
y = torch.tensor(s.target).reshape(1, 1, -1).to(device)  # (B, V, T)
x.shape, y.shape

(torch.Size([1, 1, 48]), torch.Size([1, 1, 12]))

In [77]:
# scaling check
loc, scale = compute_scale_stats(x)
ctx_s = apply_scaling(x, loc, scale)
tgt_s = apply_scaling(y, loc, scale)
print(loc.shape, scale.shape, ctx_s.shape, tgt_s.shape)
ctx_inv = invert_scaling(ctx_s, loc, scale)
tgt_inv = invert_scaling(tgt_s, loc, scale)
print("round-trip error:", (invert_scaling(ctx_s, loc, scale) - x).abs().max().item())

torch.Size([1, 1, 1]) torch.Size([1, 1, 1]) torch.Size([1, 1, 48]) torch.Size([1, 1, 12])
round-trip error: 1.7881393432617188e-07

In [81]:
# patching check
patch_size = 16
context_length = 128
output_length = 16
ctx_feats, ctx_mask = build_context_patches(ctx_s, patch_size=patch_size, context_length=context_length)
fut_feats, fut_mask = build_future_patches(tgt_s, batch_shape=ctx_feats.shape[0:2], num_output_patches=output_length // patch_size, patch_size=patch_size, context_length=context_length)
print(ctx_feats.shape, ctx_mask.shape, fut_feats.shape, fut_mask.shape)
ctx = torch.concat([ctx_feats, fut_feats], dim=2)
ctx.shape

torch.Size([1, 1, 3, 48]) torch.Size([1, 1, 3]) torch.Size([1, 1, 1, 48]) torch.Size([1, 1, 1, 16])

torch.Size([1, 1, 4, 48])

In [84]:
# embedding check
embbedding_size = 64
embed = ResidualBlock(in_dim=3*patch_size, h_dim=128, out_dim=embbedding_size).to(device)
tokens = embed(ctx)
print("tokens:", tokens.shape)
print("any NaN in tokens:", torch.isnan(tokens).any().item())

tokens: torch.Size([1, 1, 4, 64])
any NaN in tokens: False

In [72]:
fut_mask

tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.]]]],
       device='cuda:0')

In [45]:
ctx_mask

tensor([[[True, True, True]]], device='cuda:0')

In [1]:
import pandas as pd

# Load historical target values and past values of covariates
context_df = pd.read_parquet("https://autogluon.s3.amazonaws.com/datasets/timeseries/electricity_price/train.parquet")

# (Optional) Load future values of covariates
test_df = pd.read_parquet("https://autogluon.s3.amazonaws.com/datasets/timeseries/electricity_price/test.parquet")
future_df = test_df.drop(columns="target")

In [2]:
test_df

,id,timestamp,Ampirion Load Forecast,PV+Wind Forecast,target
0,DE,2017-12-12 00:00:00,20483.00,22284.005859,24.520000
1,DE,2017-12-12 01:00:00,19849.75,22878.673828,22.209999
2,DE,2017-12-12 02:00:00,19638.25,23632.283203,14.580000
3,DE,2017-12-12 03:00:00,19895.25,24635.945312,12.310000
4,DE,2017-12-12 04:00:00,20338.00,25584.935547,14.200000
5,DE,2017-12-12 05:00:00,21395.25,26489.929688,26.139999
6,DE,2017-12-12 06:00:00,24072.75,27345.125000,30.889999
7,DE,2017-12-12 07:00:00,26332.50,27729.585938,32.320000
8,DE,2017-12-12 08:00:00,27329.75,27705.193359,35.189999
9,DE,2017-12-12 09:00:00,27344.25,28046.484375,34.700001
10,DE,2017-12-12 10:00:00,27493.00,28259.966797,34.750000
11,DE,2017-12-12 11:00:00,27678.50,27927.179688,35.750000
12,DE,2017-12-12 12:00:00,27742.25,26994.121094,36.919998
13,DE,2017-12-12 13:00:00,27621.50,25359.833984,39.900002
14,DE,2017-12-12 14:00:00,27188.50,23124.015625,43.160000
15,DE,2017-12-12 15:00:00,27050.50,20662.833984,45.000000
16,DE,2017-12-12 16:00:00,27335.75,18954.791016,46.090000
17,DE,2017-12-12 17:00:00,28079.25,18155.462891,50.950001
18,DE,2017-12-12 18:00:00,27687.50,17543.630859,46.950001
19,DE,2017-12-12 19:00:00,27231.50,17154.892578,46.080002
20,DE,2017-12-12 20:00:00,25864.75,16955.433594,46.099998
21,DE,2017-12-12 21:00:00,24775.50,16948.988281,40.950001
22,DE,2017-12-12 22:00:00,23570.25,17246.566406,36.740002
23,DE,2017-12-12 23:00:00,21903.25,17630.781250,27.959999

In [3]:
future_df

    id           timestamp  Ampirion Load Forecast  PV+Wind Forecast
0   DE 2017-12-12 00:00:00                20483.00      22284.005859
1   DE 2017-12-12 01:00:00                19849.75      22878.673828
2   DE 2017-12-12 02:00:00                19638.25      23632.283203
3   DE 2017-12-12 03:00:00                19895.25      24635.945312
4   DE 2017-12-12 04:00:00                20338.00      25584.935547
5   DE 2017-12-12 05:00:00                21395.25      26489.929688
6   DE 2017-12-12 06:00:00                24072.75      27345.125000
7   DE 2017-12-12 07:00:00                26332.50      27729.585938
8   DE 2017-12-12 08:00:00                27329.75      27705.193359
9   DE 2017-12-12 09:00:00                27344.25      28046.484375
10  DE 2017-12-12 10:00:00                27493.00      28259.966797
11  DE 2017-12-12 11:00:00                27678.50      27927.179688
12  DE 2017-12-12 12:00:00                27742.25      26994.121094
13  DE 2017-12-12 13:00:00                27621.50      25359.833984
14  DE 2017-12-12 14:00:00                27188.50      23124.015625
15  DE 2017-12-12 15:00:00                27050.50      20662.833984
16  DE 2017-12-12 16:00:00                27335.75      18954.791016
17  DE 2017-12-12 17:00:00                28079.25      18155.462891
18  DE 2017-12-12 18:00:00                27687.50      17543.630859
19  DE 2017-12-12 19:00:00                27231.50      17154.892578
20  DE 2017-12-12 20:00:00                25864.75      16955.433594
21  DE 2017-12-12 21:00:00                24775.50      16948.988281
22  DE 2017-12-12 22:00:00                23570.25      17246.566406
23  DE 2017-12-12 23:00:00                21903.25      17630.781250